# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('phone', '\u0442\u0435\u043b\u0435\u0444\u043e\u043d'), ('smartphone', '\u0441\u043c\u0430\u0440\u0442\u0444\u043e\u043d'), ('tablet', '\u043f\u043b\u0430\u043d\u0448\u0435\u0442')], default='Smart', max_length=123),
        ),
    ]
