# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_auto_20170323_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='250x500px', upload_to='images', verbose_name='Image'),
        ),
    ]
