# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0005_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.TextField(default='\u041f\u0438\u0448\u0435\u043c \u0441\u044e\u0434\u0430 \u0433\u0430\u0440\u0430\u043d\u0442\u0438\u044e \u0438 \u0441\u043a\u0438\u0434\u043a\u0438 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430', verbose_name='\u043f\u0438\u0441\u0430\u0442\u044c \u0441\u044e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(max_length=500, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=25, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f \u0418\u043c\u044f \u043d\u0430 \u0430\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u043e\u043c'),
        ),
    ]
