# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0006_auto_20170324_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='pochta',
            field=models.EmailField(default=2, max_length=300, verbose_name='\u041d\u0430\u043f\u0438\u0448\u0438\u0442\u0435 \u043f\u043e\u0447\u0442\u0443'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.TextField(default='12 \u043c\u0435\u0441\u044f\u0435\u0432 \u0433\u0430\u0440\u0430\u043d\u0442\u0438\u044f \u043f\u0440\u0438 \u043d\u0430\u043b\u0438\u0447\u0438\u0438 \u0447\u0435\u043a\u0430', verbose_name='\u0421\u043a\u0438\u0434\u043a\u0438, \u0430\u043a\u0446\u0438\u0438 , \u0433\u0430\u0440\u0430\u043d\u0442\u0438\u0438'),
        ),
    ]
