# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-27 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0007_auto_20170324_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='\u041e\u0442\u0437\u0432\u044b \u043a \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0443:')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AlterField(
            model_name='buyer',
            name='pochta',
            field=models.EmailField(default='exaple@example.com', max_length=300, verbose_name='\u041d\u0430\u043f\u0438\u0448\u0438\u0442\u0435 \u043f\u043e\u0447\u0442\u0443'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazin.Buyer'),
        ),
    ]
