# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0008_auto_20170327_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='\u0416\u0435\u043b\u0430\u043d\u043d\u044b\u0439 \u0440\u0430\u0437\u043c\u0435\u0440 150x200px', upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Phone', '\u0442\u0435\u043b\u0435\u0444\u043e\u043d'), ('Smartphone', '\u0441\u043c\u0430\u0440\u0442\u0444\u043e\u043d'), ('Tablet', '\u043f\u043b\u0430\u043d\u0448\u0435\u0442')], max_length=123),
        ),
    ]
